repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, css]
        additional_dependencies:
          - prettier@3.1.0

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd poocs-web/frontend && npm run lint'
        language: system
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: false 